config/routes.rb
Ngo::Application.routes.draw do
  devise_for :admins
  resources :products, :reservations, :organizations, :officials, :educations, :targets, :operations, 
            :natures, :finances, :assets, :banks, :expenses, :incomes, :employees, :governs
  root to: "static_pages#dashboard"
  match '/newreservation', to: 'reservations#new', via: 'get'
  match '/neworganization', to: 'organizations#new', via: 'get'
  match '/newofficial', to: 'officials#new', via: 'get'
  match '/neweducation', to: 'educations#new', via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'
  match '/register', to: 'static_pages#register', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'
  match '/newtarget', to: 'targets#new', via: 'get'
  match '/newnature', to: 'natures#new', via: 'get'
  match '/newoperation', to: 'operations#new', via: 'get'
  match '/newfinance', to: 'finances#new', via: 'get'
  match '/newasset', to: 'assets#new', via: 'get'
  match '/newbank', to: 'banks#new', via: 'get'
  match '/newexpense', to: 'expenses#new', via: 'get'
  match '/newincome', to: 'incomes#new', via: 'get'
  match '/newemployee', to: 'employees#new', via: 'get'
  match '/newgovern', to: 'governs#new', via: 'get'
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(admin)
    
    if admin.role == "User"
      can :read, Organization
      can :read, Official
      can :read, StaticPage      
    end
    
    if admin.role == "NGO" 
      can :read, StaticPage
      can [:create, :read, :update],[Reservation, Organization, Official, Finance, Govern, Operation]
      can [:create, :read, :update, :destroy],[Employee, Income, Target, Bank, Asset, Expense, Education, Nature]  
    end

    if admin.org_status == "OLD NGO"
      cannot [:create, :read, :update, :destroy],[Reservation]
    end
    
    if admin.role == "admin"
      can [:create, :read, :update, :destroy], [Admin, Organization, Reservation]
    end
    
    if admin.role == "superadmin"
      can :manage, :all
    end 

    if admin.role == "STUDENT" 
      can :manage, :all
    end

  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :passport, AvatarUploader
  ROLES = %w[admin ngo]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :agreement, presence: true
  validates :role, presence: false
  
  has_one :reservation
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end
  
  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end
  
  def is?(role)
    roles.include?(role.to_s)
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_many :possessions
  has_many :finances, :through => :possessions
end

app/models/bank.rb
class Bank < ActiveRecord::Base
  has_many :fortunes
  has_many :finances, :through => :fortunes
end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
  belongs_to :finance
  belongs_to :privilege
  
  accepts_nested_attributes_for :privilege
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  belongs_to :finance
  belongs_to :income
  
  accepts_nested_attributes_for :income
end

app/models/election.rb
class Election < ActiveRecord::Base
  has_many :occurences
  has_many :finances, :through => :occurences
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :finance
  
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  has_many :sectors
  has_many :finances, :through => :sector
  has_many :projects
  has_many :finances, :through => :projects
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  has_one :employee, :class_name=> "Employee"
  has_one :govern, :class_name=> "Govern"
  has_many :waivers, :class_name=> "Waiver"
  has_many :possessions
  has_many :assets, :through => :possessions, :class_name=> "Asset"
  has_many :donors
  has_many :incomes, :through => :donors, :class_name=> "Income"
  has_many :sectors
  has_many :expenses, :through => :sectors, :class_name=> "Sector"
  has_many :fortunes
  has_many :banks, :through => :fortunes, :class_name=> "Fortune"
  has_many :projects
  has_many :expenses, :through => :projects, :class_name=> "Project"
  has_many :benefits
  has_many :privileges, :through => :benefits, :class_name=> "Privilege"
  has_many :trained_members
  has_many :trainings, :through => :trained_members, :class_name=> "Training"
  has_many :locals
  has_many :local_contributions, :through => :locals, :class_name=> "LocalContribution"
  has_many :contributions
  has_many :government_contributions, :through => :contributions, :class_name=> "GovernmentContribution"
  has_many :collaborations
  has_many :collaborates, :through => :collaborations, :class_name=> "Collaborate"
  has_many :occurences
  has_many :elections, :through => :occurences, :class_name=> "Election"
  belongs_to :organization
  
  accepts_nested_attributes_for :possessions, :reject_if => :all_blank, :allow_destroy => true 
  accepts_nested_attributes_for :donors, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :sectors, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :fortunes, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :employee, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :projects, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :benefits, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :trained_members, :reject_if => :all_blank, :allow_destroy => true     
  accepts_nested_attributes_for :locals, :reject_if => :all_blank, :allow_destroy => true  
  accepts_nested_attributes_for :contributions, :reject_if => :all_blank, :allow_destroy => true  
  accepts_nested_attributes_for :waivers, :reject_if => :all_blank, :allow_destroy => true  
  accepts_nested_attributes_for :collaborations, :reject_if => :all_blank, :allow_destroy => true  
  accepts_nested_attributes_for :govern, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :occurences, :reject_if => :all_blank, :allow_destroy => true
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  belongs_to :finance
  belongs_to :bank
  
  accepts_nested_attributes_for :bank
end

app/models/govern.rb
class Govern < ActiveRecord::Base
  belongs_to :finance
end

app/models/income.rb
class Income < ActiveRecord::Base
  has_many :donors
  has_many :finances, :through => :donor
end

app/models/local.rb
#contribution by local people
class Local < ActiveRecord::Base
  belongs_to :finance
  belongs_to :local_contribution
  
  accepts_nested_attributes_for :local_contribution
end

app/models/nature.rb
class Nature < ActiveRecord::Base
  #has_many :dispositions
  #has_many :organizations, :through=> :dispositions
  has_and_belongs_to_many :organizations
end

app/models/product.rb
class Product < ActiveRecord::Base
    

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :finance
  belongs_to :expense
  
  accepts_nested_attributes_for :expense
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  belongs_to :finance
  belongs_to :expense
  
  accepts_nested_attributes_for :expense
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/target.rb
class Target < ActiveRecord::Base
  has_and_belongs_to_many :organizations
end

app/models/waiver.rb
class Waiver < ActiveRecord::Base
  belongs_to :finance
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_authorization_check 
  #load_and_authorize_resource
  before_filter :authenticate_admin!
  def home
  end
  
  def help
  end
  
  def contact
  end
  
  def sitemap
  end
  
  def dashboard
  end
  
  def error
  end
  
  def register
    
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/404.html.erb
<body class="body-404">
    <div class="error-header"> </div>
    <div class="container ">
        <section class="error-container text-center">
            <h1>404</h1>
            <div class="error-divider">
                <h2>page not found</h2>
                <p class="description">We Couldn’t Find This Page</p>
            </div>
            <a href="index.html" class="return-btn"><i class="fa fa-home"></i>Home</a>
        </section>
    </div>
</body>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:header, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact NGO Coordination Board of Kenya about the solution at the
  <a href="#">NGO page</a>.
</p>

app/views/static_pages/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<% breadcrumb :root %>

<div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="databox bg-white radius-bordered">
                        <div class="databox-left bg-themesecondary">
                            <div class="databox-piechart">
                                <div data-toggle="easypiechart" class="easyPieChart" data-barcolor="#fff" data-linecap="butt" data-percent="0" data-animate="500" data-linewidth="3" data-size="47" data-trackcolor="rgba(255,255,255,0.1)"><span class="white font-90">50%</span></div>
                            </div>
                        </div>
                        <div class="databox-right">
                        	<% if current_admin.org_status=="NEW NGO" %>
	                            <span class="databox-number themesecondary">GET STARTED</span>
	                            <div class="databox-text darkgray">
	                            	<%= link_to "Make a Class reservation", '#' %></div>
	                            <div class="databox-stat themesecondary radius-bordered">
	                                <i class="stat-icon icon-lg fa fa-tasks"></i>
	                            </div>
	                        <% else %>
	                        	<span class="databox-number themesecondary">GET STARTED</span>
	                            <div class="databox-text darkgray">
	                            	<%= link_to "Enter your money markets requirements details", '#' %></div>
	                            <div class="databox-stat themesecondary radius-bordered">
	                                <i class="stat-icon icon-lg fa fa-tasks"></i>
	                            </div>
	                        <% end %>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="databox bg-white radius-bordered">
                        <div class="databox-left bg-themethirdcolor">
                            <div class="databox-piechart">
                                <div data-toggle="easypiechart" class="easyPieChart" data-barcolor="#fff" data-linecap="butt" data-percent="15" data-animate="500" data-linewidth="3" data-size="47" data-trackcolor="rgba(255,255,255,0.2)"><span class="white font-90">15%</span></div>
                            </div>
                        </div>
                        <div class="databox-right">
                            <span class="databox-number themethirdcolor">1</span>
                            <div class="databox-text darkgray">NEW INVOICE</div>
                            <div class="databox-stat themethirdcolor radius-bordered">
                                <i class="stat-icon  icon-lg fa fa-envelope-o"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="databox bg-white radius-bordered">
                        <div class="databox-left bg-themeprimary">
                            <div class="databox-piechart">
                                <div id="users-pie" data-toggle="easypiechart" class="easyPieChart" data-barcolor="#fff" data-linecap="butt" data-percent="76" data-animate="500" data-linewidth="3" data-size="47" data-trackcolor="rgba(255,255,255,0.1)"><span class="white font-90">76%</span></div>
                            </div>
                        </div>
                        <div class="databox-right">
                            <span class="databox-number themeprimary"></span>
                            <div class="databox-text darkgray">
                            	STATUS OF APPLICATION
                            	<% if current_admin.reservation %>
                            		NO RESERVATIONS MADE 
                            	<% else %>
                            		<%= current_admin.reservation %>
                            	<%end%>
                            </div>
                            <div class="databox-state bg-themeprimary">
                                <i class="fa fa-check"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="databox bg-white radius-bordered">
                        <div class="databox-left no-padding">
                        	<%= image_tag("#", alt: "constitution", :width=> "65px", :height=>"65px")%>
                            
                        </div>
                        <div class="databox-right padding-top-20">
                            <div class="databox-stat palegreen">
                                <i class="stat-icon icon-xlg fa fa-book"></i>
                            </div>
                            <div class="databox-text darkgray">Privacy policy</div>
                            <div class="databox-text darkgray">
                            	<%= link_to "DOWNLOAD HERE", "#"%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end of header part-->
    
    

app/views/static_pages/error.html.erb
<% provide(:title, '404') %>
<div class="body-404">
    <div class="error-header"> </div>
    <div class="container ">
        <section class="error-container text-center">
            <h1>404</h1>
            <div class="error-divider">
                <h2>page not found</h2>
                <p class="description">We Couldn’t Find This Page</p>
            </div>
            <%= link_to "Home", root_url, :class=>'return-btn' %>
				              
        </section>
    </div>
</div>
<!--Body Ends-->

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<% provide(:header, 'Home') %>
<h1>Help</h1>
<p>
  Check the indexes or enter your search parameter
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% breadcrumb :root %>
<% provide(:header, 'Home') %>
<%= render 'layouts/content'%>

app/views/static_pages/register.html.erb
<% provide(:title, "Application Step 2") %>
<% provide(:header, 'Application Step 2') %>
<!-- Page Content -->
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">APPLICATION</h1>
            <!-- /.row -->
			<div class="row">
				<div class="col-lg-12">
					Congratulations for meeting requirements for registration of NGOs in Kenya. To complete the process, 
					follow the laid processes below.
					<ol>
						
						<li><%= link_to 'Add Organization Details', neworganization_path  %></li>	
						<li><%= link_to 'Add Officials Details', newofficial_path  %></li>				
					</ol>
					<!-- /.panel -->
				</div>
				<!-- /.col-lg-6 -->                
			</div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->